[build]
  base = "frontend"
  publish = "frontend/.next"
  command = "npm install && npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.18.1"
  NEXT_PUBLIC_API_URL = "https://futurelinked.netlify.app"
  NEXT_PUBLIC_GOOGLE_ADSENSE_ID = "ca-pub-5675694305993193"
