[build]
  command = "npm install --prefix backend && npm install --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/.next"
  functions = "backend/netlify/functions"

[build.environment]
  NODE_VERSION = "20.18.1"
  AFFINDA_API_KEY = "aff_d21f7b34a80a49d4ea62408e9e42e32cfc94fe84"
  AFFINDA_WORKSPACE = "YQAsNzjw"

[functions]
  node_bundler = "esbuild"
  included_files = ["backend/node_modules/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/cv/*"
  to = "/.netlify/functions/api/cv/:splat"
  status = 200
